### PR TITLE
make require_once(ABSPATH . 'wp-admin/includes/upgrade.php'); call unique

### PR DESCRIPTION
**Pull request by Presskopp**

### CODE REVIEW

**Review by hassantafreshi — COMMENTED** [review]
Do you test this ?

**Comment by Presskopp** [comment]
No I didn't, it's more an idea you can check

**Review by hassantafreshi — COMMENTED** [review]
I attempted it before, and the tables were not created properly

**Comment by hassantafreshi** [comment]
let check again!

**Pull request merged**
