### PR TITLE
Minor updates

### PR DESCRIPTION
**Pull request by thaikolja**
This is the small beginning of an update that could make it into 3.5.8. Please check my changes and approve my merge request (unless I f**** up, of course) for the 3.5.8-alpha1 tag. Also, important: Minimum PHP is NOT 5.5, as you stated. It’s 7.1, at least. I changed that, too, in the `readme.txt`.

Signed-off-by: thaikolja <kolja.nolte@gmail.com>

### CODE REVIEW

**Comment by hassantafreshi** [comment]
Thanks for commit. I will check and respond to you about this commit.  try to be polite !

**Comment by hassantafreshi** [comment]
Please update your repo and send request again because this branch has conflicts with last update.

Please consider this todo list :
- Do not change [emsfb.php](https://github.com/hassantafreshi/easy-form-builder/pull/33/files#diff-0c94352cca55193eae6adde1851799f689ac084b9ae45c0b03e8b708fd12bbe7) file.
- Do not change [class-Emsfb-public.php](https://github.com/hassantafreshi/easy-form-builder/pull/33/files#diff-dd46749d887cb7c0e36f96e40b5bd22b2fa4d93cc9a481f2ca0515322f84b3d8)
- Do not change files on vendor path.

**Comment by thaikolja** [comment]
> Thanks for commit. I will check and respond to you about this commit. try to be polite !

Excuse me?! Your plugin does not work with the PHP version you wrote, it is just a fact that you can test yourself. What would be impolite about that?

> Please consider this todo list 

No, thank you, I'm not wasting any more of my or your time by being told what I'm allowed to do and what not.

Run your plugin in a Docker container or something with various server settings, and you'll see that it's unusable in certain cases. I wonder why you keep this plugin as an open GitHub repository when you don't allow users to touch crucial and basic files.

Your pro version can be nulled within 2 minutes, too. If you don't address security changes to protect your users, then I feel responsible for publishing the safety issues (and bugs) on one of the many WordPress security websites to warn your users of potential security risks.

In addition to that, your plugin is terrible when it comes to backward compatibility. I had intended to help with these issues, but that's no longer necessary.

A piece of advice: **If you can't take criticism, don't do open-source.**

Good luck with your plugin. Please feel free to close this thread now.

**Comment by hassantafreshi** [comment]
I say be polite because you used F word ! And asked you try commit again because your request has conflicts with last update.
I will be happy if anyone be hand not act ...! 

If you find the problems do what you want .
I know the plugin can be nulled in two minutes and if you find any security bug publish it on the security site and it will be my Glad,  you help the Wordpress community including my users.

**Pull request closed without merging**
